"""Stage 5. Turn the model and the probe into a package a stranger can use, by generation rather than by
writing. The driver is the template's generic runtime with the model bundled beside it; the reference,
the evidence, the tests and the manifest are rendered from the model and the probe output. Nothing here
can repair a model, because nothing here reads the device.

Written against the four complaints every reuse agent of run real3 made: the evidence cited files the
package did not ship, nothing said whether the printed or the full-precision value was the reading, the
state the device was left in was unstated, and no accuracy or range was evidenced. Each is answered here
by construction, and the last is answered by saying plainly that the package does not evidence it.
"""
import json, os, random, shutil, subprocess, tempfile, hashlib
from pathlib import Path

from . import core, runner

TEMPLATE = os.path.join(core.BENCH, "toolchain", "template")
SHIM = os.path.join(core.BENCH, "tools", "pyftdi_shim")


def _ops_table(model):
    rows = []
    ops = model["operations"]
    def fmt(s):
        o = s.get("op")
        if o == "reg_write":
            return f"write {s['reg']} = {' '.join(str(b) for b in s['bytes'])}"
        if o == "reg_read":
            return f"read {s['len']} byte(s) from {s['reg']}" + (f" as {s['as']}" if s.get("as") else "")
        if o == "delay_ms":
            return f"wait {s['ms']} ms"
        if o == "raw_write":
            return f"write raw {' '.join(str(b) for b in s.get('bytes', []))}"
        if o == "raw_read":
            return f"read {s.get('len')} raw byte(s)"
        return o
    for step in ops.get("init", []):
        rows.append(("init", fmt(step)))
    for st in model.get("state", []):
        rows.append((f"state {st.get('name', '')}".strip(), fmt(st)))
    for step in ops.get("identify", []):
        rows.append(("identify", fmt(step)))
    for step in ops.get("measure", []):
        rows.append(("measure", fmt(step)))
    for name, steps in ops.items():
        if name in ("init", "identify", "measure"):
            continue
        for step in steps:
            rows.append((f"op {name}", fmt(step)))
    return rows


def _reference(model, probe, name, version):
    dev = model.get("device") or {}
    ch = model.get("channel") or {}
    outs = (model.get("conversion") or {}).get("outputs") or {}
    conf = model.get("confidence") or {}
    ident = model.get("identity") or {}
    sample = (probe.get("samples") or [{}])[0].get("values", {})
    L = [f"# {name} {version}, device reference", "",
         "This package was generated by the emit stage of a driver compiler from an interface model and a "
         f"probe record labelled {probe.get('evidence_kind', 'unlabelled')}. Replay and unlabelled records are not physical observations. The driver puts "
         "on the bus exactly the operations the model lists, in the model's order, and converts with the "
         "model's own arithmetic. The model is bundled verbatim as `driver/model.json` and `driver/convert.py`, "
         "and the probe output as `probe.json`; `manifest.json` carries the hash of each. Every statement "
         "below is traced in `EVIDENCE.md`, and every file it cites ships inside this package.", "",
         "## What the device is", ""]
    if dev.get("name"):
        L.append(f"The model names the part as {dev['name']}, with confidence {dev.get('confidence', 0)}. "
                 f"That name comes from the description the model was built from, not from the bus.")
    else:
        L.append("The model does not name the part. Nothing in this package identifies it beyond the "
                 "identity byte below.")
    if ident.get("expect"):
        L.append(f"The model expects the identity read to return one of {', '.join(ident['expect'])}. "
                 f"The probe run read {probe.get('identity')} at address {probe.get('address')}. That byte is "
                 f"the strongest evidence here that the device is what the model says.")
    L += ["", "## What it measures", "",
          "| output | unit | seen in the probe run | range and accuracy |", "|---|---|---|---|"]
    for k, u in outs.items():
        seen = f"{sample[k]:.4g}" if k in sample else "not returned"
        L.append(f"| `{k}` | {u} | {seen} | not evidenced by this package |")
    L += ["",
          "The middle column is one reading taken when the package was generated, given for orientation "
          "only; it is not a calibration and not a range. Neither the accuracy of these quantities nor the "
          "range over which they hold is evidenced by anything in this package: the model was built from a "
          "description of the device, and the probe confirmed only that the device answers and returns "
          "numbers. Treat a reading outside what you expect as unexplained rather than as out of range.", "",
          "### Precision", "",
          "`measure` prints values rounded for reading. `--json` prints the same numbers at full precision, "
          "and is what you should parse. The number of digits reflects the step of the model's conversion "
          "arithmetic, which is not a statement about the device's accuracy.", "",
          "## How to use it", "",
          "From the `package/` directory, with Python 3 and pyftdi installed:", "",
          "```", "python -m driver --url ADAPTER_URL info", "python -m driver --url ADAPTER_URL --allow-write --json measure", "python -m driver --help", "```", "",
          "Replace ADAPTER_URL with the selected ftdi:// adapter URL. Add --allow-write only when granting the model write access.", "",
          "From Python: `import sys; sys.path.insert(0, 'package')` then `from driver import Device` and "
          "`with Device(url=selected_url, allow_write=True) as dev: print(dev.measure().values)`.", "",
          "Every invocation is one session in the model's order: address discovery, init, the state reads, "
          "the identity read, then the command. One line per reply, `OK key=value ...` or `ERR code=...`. "
          "Exit codes: 0 ok, 1 refused or usage, 2 identity mismatch, 3 no acknowledge, 4 bus or USB error.", "",
          "## The state the device is left in", ""]
    inits = [f"`{s['reg']}` = {' '.join(str(b) for b in s['bytes'])}" for s in model["operations"].get("init", [])
             if s.get("op") == "reg_write"]
    if inits:
        L.append("This package does not restore the device to the state it was in before the session. Every "
                 "invocation runs the model's init, which writes " + "; ".join(inits) + ". When the command "
                 "returns, the device is left in that state and keeps doing whatever that configuration makes "
                 "it do until something else changes it. Use `--no-init` to run a command without touching "
                 "the configuration.")
    else:
        L.append("The model's init writes nothing, so this package leaves the device's configuration as it "
                 "found it.")
    L += ["", "## How it is wired", "", ch.get("wiring") or "The model records no wiring note.",
          f"\nChannel: {ch.get('type')}, address {ch.get('address_7bit')}"
          + (f" (alternatives {', '.join(ch.get('address_alternatives', []))})" if ch.get("address_alternatives") else "")
          + f", {ch.get('speed_hz')} Hz.", "", "## Protocol", "",
          "| step | what goes on the bus |", "|---|---|"]
    for step, what in _ops_table(model):
        L.append(f"| {step} | {what} |")
    period = model.get("measure_period_ms")
    if period:
        L.append("")
        L.append(f"The model's measurement period is {period} ms, with the first sample "
                 f"{model.get('measure_wait_ms', 0)} ms after init.")
    saf = model.get("safety") or {}
    L += ["", "## Safety limits", "",
          f"Registers the model gives evidence for reading: {', '.join(saf.get('safe_reads', [])) or 'none listed'}.",
          f"Writes the model performs, and which are therefore known to be survivable on this device: "
          f"{', '.join(saf.get('known_safe_writes', [])) or 'none'}.",
          f"Writes the model forbids: {', '.join(saf.get('never', [])) or 'none listed'}.", "",
          "`read` outside the listed registers and `write` anywhere not listed as known-safe are refused "
          "unless `--force` is passed. Everything not listed is unverified rather than known to be harmful: "
          "the model has no evidence either way, which is why the driver will not do it for you.", "",
          "## What the model was unsure about", ""]
    low = sorted(((k, v) for k, v in conf.items() if isinstance(v, (int, float))), key=lambda kv: kv[1])
    if low:
        L.append("The model's own confidence, lowest first: "
                 + "; ".join(f"{k} {v}" for k, v in low)
                 + ". A low number is the model saying its evidence for that part was weak.")
    else:
        L.append("The model records no confidences.")
    return "\n".join(L) + "\n"


def _evidence(model, probe, name):
    L = [f"# {name}, evidence", "",
         "Every claim in `REFERENCE.md`, and where it comes from. Two sources only, both shipped in this "
         "package: `driver/model.json`, which carries the model's own provenance for each entry, and "
         "`probe.json`, the output of executing that model on the device.", "",
         "## The model's provenance", "", "| model entry | source | how |", "|---|---|---|"]
    for p in model.get("provenance", []):
        L.append(f"| {p.get('item', '')} | {str(p.get('source', ''))[:120]} | {str(p.get('how', ''))[:160]} |")
    if not model.get("provenance"):
        L.append("| (none recorded) | | |")
    L += ["", "## What the probe confirmed", "",
          f"The supplied {probe.get('evidence_kind', 'unlabelled')} probe record reports an answer at {probe.get('address')}. "
          f"The identity read returned {probe.get('identity')}, which the model "
          f"{'accepts' if probe.get('identity_ok') else 'does NOT accept'}.", "",
          "| sample | raw bytes | converted |", "|---|---|---|"]
    for i, s in enumerate((probe.get("samples") or [])[:5], 1):
        vals = " ".join(f"{k}={v:.4g}" for k, v in s.get("values", {}).items())
        L.append(f"| {i} | `{s.get('raw', '')}` | {vals} |")
    L += ["", "Those converted numbers are what the bundled `convert.py` returns for those raw bytes, so "
          "any reading this package produces can be re-derived from its own raw bytes by anyone who has the "
          "package: the conversion ships here. `tests/test_live.py` does not re-derive them, because it "
          "would be calling the same code; it asserts the identity byte, that a first sample after init is "
          "valid, that every declared output comes back finite, and that an unevidenced write is refused.", "",
          "## What is not evidenced", "",
          "The part's accuracy, the range over which its readings hold, its behaviour outside the "
          "configuration the model's init sets, and the meaning of any register the model does not read. "
          "None of these follow from the model or from the probe, and this package does not assert them.", ""]
    return "\n".join(L) + "\n"


def _tests(model, name):
    outs = list(((model.get("conversion") or {}).get("outputs") or {}).keys())
    saf = model.get("safety") or {}
    safe_writes = " ".join(saf.get("known_safe_writes", []))
    probe_reg = None
    for r in range(0x00, 0x100):                       # a register the model never writes: the refusal test
        h = "0x%02X" % r
        if h.lower() not in safe_writes.lower() and ("0x%02x" % r) not in safe_writes.lower():
            probe_reg = h
            break
    return '''"""Regression suite for %s: invariants only, never a remembered reading.

Run from the package directory with GD_REGISTER_URL set to the selected ftdi:// adapter.
Grant writes explicitly with GD_REGISTER_ALLOW_WRITE=1 when required, then run: python tests/test_live.py

Every assertion here must hold whatever the device is measuring at the time, so the suite does not go
stale when the world changes. It asserts nothing about accuracy or range, because the package evidences
neither.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
sys.path.insert(0, PKG)
from driver import Device, RefusedError, load_model  # noqa: E402

OUTPUTS = %r
REFUSE_REG = %r
fails = []


def check(name, ok, detail=""):
    print(("PASS  " if ok else "FAIL  ") + name + (("  " + detail) if detail else ""))
    if not ok:
        fails.append(name)


model, _mod, _entry = load_model()
expect = [int(str(e), 16) for e in (model.get("identity") or {}).get("expect", [])]

with Device(url=os.environ.get("GD_REGISTER_URL"), allow_write=os.environ.get("GD_REGISTER_ALLOW_WRITE") == "1") as dev:
    info = dev.info()
    check("identity byte is one the model expects",
          (not expect) or int(str(info["identity"]), 16) in expect,
          "read %%s, model expects %%s" %% (info["identity"], [hex(e) for e in expect]))
    s1 = dev.measure()
    check("first sample after init is valid", bool(s1.valid), "skipped=%%s" %% (s1.skipped,))
    check("every declared output is returned", set(OUTPUTS) <= set(s1.values), "got %%s" %% sorted(s1.values))
    check("every value is a finite number",
          all(v == v and abs(v) != float("inf") for v in s1.values.values()), str(s1.values))
    check("every output carries a unit", all(k in s1.units for k in s1.values), str(s1.units))
    s2 = dev.measure()
    check("a second measurement also returns every output", set(OUTPUTS) <= set(s2.values), str(s2.values))
    check("the identity byte is stable across reads", dev.info()["identity"] == info["identity"])
    try:
        dev.write(int(REFUSE_REG, 16), 0x00)
        check("a write the model gives no evidence for is refused", False, "it was allowed")
    except RefusedError:
        check("a write the model gives no evidence for is refused", True, "register %%s" %% REFUSE_REG)

print(("FAILED: " + ", ".join(fails)) if fails else "all invariants hold")
sys.exit(1 if fails else 0)
''' % (name, outs, probe_reg)


@core.tool("emit_package")
def emit_package(run_dir, model_dir, probe, wiring=None, name=None, version="1.0.0", **_):
    """Generate the device package from the model and the probe output."""
    run = core.resolve_run(run_dir)
    md = model_dir if os.path.isabs(model_dir) else os.path.join(core.BENCH, model_dir)
    pp = probe if os.path.isabs(probe) else os.path.join(core.BENCH, probe)
    from . import interface
    model, _sha = interface.load(md)
    if model.get("schema") in interface.SCHEMAS:
        return interface.emit_package(run_dir, md, pp, name=name, version=version)
    pr = json.loads(Path(pp).read_text(encoding="utf-8"))
    dev = (model.get("device") or {}).get("name") or "device"
    name = name or ("".join(c.lower() if c.isalnum() else "-" for c in dev).strip("-")[:28]
                    + "-" + (model.get("channel") or {}).get("type", "bus"))
    pkg = os.path.join(run, "emit", "package")
    os.makedirs(os.path.dirname(pkg), exist_ok=True)
    pkg = tempfile.mkdtemp(prefix="package-", dir=os.path.dirname(pkg))
    os.makedirs(os.path.join(pkg, "driver"))
    os.makedirs(os.path.join(pkg, "tests"))
    for f in ("device.py", "__init__.py", "__main__.py"):
        s = Path(TEMPLATE, "driver", f).read_text(encoding="utf-8")
        s = s.replace("@@NAME@@", name).replace("@@VERSION@@", version)
        Path(pkg, "driver", f).write_text(s, encoding="utf-8", newline="\n")
    shutil.copyfile(os.path.join(md, "model.json"), os.path.join(pkg, "driver", "model.json"))
    shutil.copyfile(os.path.join(md, (model.get("conversion") or {}).get("module", "convert.py")),
                    os.path.join(pkg, "driver", "convert.py"))
    shutil.copyfile(pp, os.path.join(pkg, "probe.json"))
    if wiring:
        w = wiring if os.path.isabs(wiring) else os.path.join(core.BENCH, wiring)
        if os.path.exists(w):
            shutil.copyfile(w, os.path.join(pkg, "WIRING.md"))
    Path(pkg, "REFERENCE.md").write_text(_reference(model, pr, name, version), encoding="utf-8", newline="\n")
    Path(pkg, "EVIDENCE.md").write_text(_evidence(model, pr, name), encoding="utf-8", newline="\n")
    Path(pkg, "tests", "test_live.py").write_text(_tests(model, name), encoding="utf-8", newline="\n")
    Path(pkg, "tests", "README.md").write_text(
        "# Regression suite\n\nRun from the package directory with the device on the bus:\n\n```\n"
        "python tests/test_live.py\n```\n\nSet GD_REGISTER_URL to the selected ftdi:// adapter URL. "
        "When the model writes, set GD_REGISTER_ALLOW_WRITE=1 as an explicit grant.\n\nEvery assertion is an invariant, not a remembered reading: the "
        "identity byte the model expects, that a first sample after init is valid, that every declared "
        "output comes back as a finite number, and that the identity is stable across reads. The suite "
        "therefore stays valid when the thing the device is measuring changes.\n", encoding="utf-8", newline="\n")
    files = core.sha_tree(pkg)
    manifest = {"name": name, "version": version,
                "kind": "device package generated from interface-model/1 by the driver compiler's emit stage",
                "generated": core.now(), "source_evidence_kind": pr.get("evidence_kind", "unlabelled"),
                "entry": {"reference": "REFERENCE.md", "evidence": "EVIDENCE.md", "driver": "driver/",
                          "cli": "python -m driver", "tests": "tests/test_live.py", "probe": "probe.json"},
                "requires": ["python>=3.11", "pyftdi>=0.57"],
                "device": model.get("device"), "channel": model.get("channel"),
                "outputs": (model.get("conversion") or {}).get("outputs"),
                "confidence": model.get("confidence"),
                "files": files}
    with open(os.path.join(pkg, "manifest.json"), "w", encoding="utf-8", newline="\n") as stream:
        json.dump(manifest, stream, indent=1)
    manifest_sha = core.sha256(os.path.join(pkg, "manifest.json"))
    Path(pkg, "manifest.sha256").write_text(manifest_sha + "\n", encoding="utf-8")
    files = core.sha_tree(pkg)
    return {"manifest_sha256": manifest_sha, "package_dir": core.label(pkg), "name": name, "version": version,
            "file_count": len(files), "_files": files}


def _shim_run(pkg, regs, address, args=("--json", "measure")):   # global flags precede the command in this CLI
    with tempfile.TemporaryDirectory() as td:
        rf = os.path.join(td, "regs.bin"); lf = os.path.join(td, "log.json")
        Path(rf).write_bytes(regs)
        env = dict(os.environ, PYTHONPATH=SHIM + os.pathsep + os.environ.get("PYTHONPATH", ""),
                   REGISTER_SHIM_REGS=rf, REGISTER_SHIM_LOG=lf, REGISTER_SHIM_ACK=hex(address))
        r = subprocess.run([core.VENV_PY, "-m", "driver", "--url", "ftdi://replay/1", "--allow-write", *args], cwd=pkg, env=env,
                           capture_output=True, text=True, timeout=120)
        log = json.loads(Path(lf).read_text(encoding="utf-8")) if os.path.exists(lf) else []
    return r.stdout.strip(), r.stderr.strip(), log


def _register_integrity(pkg, model_dir=None, expected_manifest_sha256=None):
    """Read before executing. Converter Python remains candidate code, pinned to its source."""
    from interface_runtime.package import package_files
    try:
        root = Path(pkg)
        if (root / "manifest.json").is_symlink() or (root / "manifest.sha256").is_symlink():
            raise ValueError("manifest may not be a symlink")
        manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
        actual_sha = core.sha256(root / "manifest.json")
        if ((root / "manifest.sha256").read_text(encoding="utf-8").strip() != actual_sha or
                expected_manifest_sha256 is not None and expected_manifest_sha256 != actual_sha):
            raise ValueError("manifest checksum/pin mismatch")
        files = package_files(root)
        if files != manifest.get("files"):
            raise ValueError("package file inventory/hash mismatch")
        model = json.loads((root / "driver/model.json").read_text(encoding="utf-8"))
        if model_dir is not None:
            source = Path(model_dir)
            if (files.get("driver/model.json") != core.sha256(source / "model.json") or
                files.get("driver/convert.py") != core.sha256(source / model.get("conversion", {}).get("module", "convert.py"))):
                raise ValueError("package belongs to different model/converter bytes")
        name, version = manifest["name"], manifest["version"]
        trusted = {}
        for filename in ("device.py", "__init__.py", "__main__.py"):
            value = Path(TEMPLATE, "driver", filename).read_text(encoding="utf-8")
            value = value.replace("@@NAME@@", name).replace("@@VERSION@@", version)
            trusted["driver/" + filename] = hashlib.sha256(value.encode("utf-8")).hexdigest()
        trusted["tests/test_live.py"] = hashlib.sha256(_tests(model, name).encode("utf-8")).hexdigest()
        trusted["driver/convert.py"] = files.get("driver/convert.py")
        if trusted != {key: value for key, value in files.items() if key.endswith(".py")}:
            return {"ok": False, "integrity_ok": True, "runtime_current": False,
                    "defects": [{"where": "runtime", "what": "package Python differs from current trusted templates"}], "_exit": 1}
        return {"ok": True, "integrity_ok": True, "runtime_current": True, "manifest": manifest, "manifest_sha256": actual_sha,
                "manifest_pin_verified": expected_manifest_sha256 is not None, "_exit": 0}
    except (OSError, ValueError, TypeError, KeyError) as exc:
        return {"ok": False, "integrity_ok": False,
                "defects": [{"where": "package", "what": str(exc)}], "_exit": 1}


def _register_snapshot(pkg, temporary, checked):
    snapshot = Path(temporary) / "package"
    snapshot.mkdir()
    for name in [*checked["manifest"]["files"], "manifest.json", "manifest.sha256"]:
        destination = snapshot / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(Path(pkg) / name, destination, follow_symlinks=False)
    return str(snapshot)


@core.tool("emit_check")
def emit_check(package_dir, model_dir=None, seeds=20, seed=0, tol_rel=1e-9, expected_manifest_sha256=None, **_):
    """Does the package do what its model says, and nothing else?

    Runs the package against register files drawn from the model's own read ranges, under a stand-in for
    the bus, and requires its numbers to equal the model's conversion on the same bytes and the set of
    registers it touches to equal the set the model touches. No ground truth and no device knowledge, so
    this check works for any register device.
    """
    pkg = package_dir if os.path.isabs(package_dir) else os.path.join(core.BENCH, package_dir)
    from . import interface
    if model_dir is None:
        if interface.is_interface_package(pkg):
            return interface.emit_check(pkg, expected_manifest_sha256=expected_manifest_sha256)
        return {'ok': False, 'defects': [{'where': 'model_dir',
                'what': 'a register package requires an explicit model_dir'}], '_exit': 1}
    md = model_dir if os.path.isabs(model_dir) else os.path.join(core.BENCH, model_dir)
    loaded, _sha = interface.load(md)
    schema = loaded.get("schema")
    if schema in interface.SCHEMAS:
        return interface.emit_check(pkg, md, expected_manifest_sha256)
    checked = _register_integrity(pkg, md, expected_manifest_sha256)
    if not checked["ok"]:
        return checked
    with tempfile.TemporaryDirectory() as temporary:
        snapshot = _register_snapshot(pkg, temporary, checked)
        verified = _register_integrity(snapshot, md, checked["manifest_sha256"])
        if not verified["ok"]:
            return verified
        return {**_check_register_snapshot(snapshot, md, seeds, seed, tol_rel),
                "integrity_ok": True, "runtime_current": True,
                "manifest_pin_verified": expected_manifest_sha256 is not None}


def _check_register_snapshot(pkg, md, seeds, seed, tol_rel):
    model, convert = runner.load_model(md)
    want_reads = runner.read_ranges(model)
    want_writes = runner.write_set(model, convert)
    rng = random.Random(seed)
    bad_vals = bad_foot = skipped = 0
    worst = 0.0
    notes = []
    for i in range(int(seeds)):
        regs = runner.random_register_file(model, rng)
        exp, _ = runner.model_values(model, convert, regs)
        if exp is None:
            skipped += 1
            continue
        out, err, log = _shim_run(pkg, regs, runner.for_register_file(model)[1])
        got = {}
        for line in out.splitlines():
            try:
                o = json.loads(line)
            except Exception:
                continue
            vals = o.get("values") if isinstance(o.get("values"), dict) else o
            got = {k: v for k, v in vals.items() if k in exp and isinstance(v, (int, float))}
        if not got:
            bad_vals += 1
            if len(notes) < 2:
                notes.append(f"seed {i}: no parsable values. stdout {out[:120]!r} stderr {err[-200:]!r}")
        else:
            e = max(abs(got.get(k, 1e18) - exp[k]) / max(1.0, abs(exp[k])) for k in exp)
            worst = max(worst, e)
            if e > tol_rel:
                bad_vals += 1
                if len(notes) < 3:
                    notes.append(f"seed {i}: package {got} vs model {exp}")
        reads, writes = set(), set()   # compared even when the values failed, or a crash hides a footprint
        for entry in log:
            kind, a, b = entry
            if kind == "read":
                reads |= set(range(a, a + b))
            elif kind == "write":
                writes.add((a, bytes(b)))
        if reads != want_reads or writes != want_writes:
            bad_foot += 1
            if bad_foot == 1:
                notes.append("footprint differs: extra reads "
                             f"{sorted(hex(x) for x in reads - want_reads)[:6]}, missing "
                             f"{sorted(hex(x) for x in want_reads - reads)[:6]}, extra writes "
                             f"{[(hex(r), d.hex()) for r, d in writes - want_writes][:3]}, missing "
                             f"{[(hex(r), d.hex()) for r, d in want_writes - writes][:3]}")
    run_n = int(seeds) - skipped
    ok = bad_vals == 0 and bad_foot == 0 and run_n > 0
    return {"ok": ok, "seeds_run": run_n, "seeds_skipped_out_of_domain": skipped,
            "values_mismatched": bad_vals, "footprint_mismatched": bad_foot,
            "worst_relative_error": worst, "_exit": 0 if ok else 1, "_notes": notes}


@core.tool("emit_test_live")
def emit_test_live(package_dir, run_dir=None, binding=None, operations=None, parameters=None, allow_effects=None,
                   model_dir=None, expected_manifest_sha256=None, **_):
    """Run the package's own regression suite on the live bus.

    An interface package (manifest interface-package/1) has no suite: each of `operations` (default the model's
    identity operation) runs once through the package's own command line with the caller's `binding`, the
    `parameters` given for it and the `allow_effects` grants. Exit 4 means a transport fault, inconclusive."""
    pkg = package_dir if os.path.isabs(package_dir) else os.path.join(core.BENCH, package_dir)
    from . import interface
    if interface.is_interface_package(pkg):
        return interface.emit_test_live(run_dir, pkg, binding, operations=operations, parameters=parameters,
                                        allow_effects=allow_effects, model_dir=model_dir,
                                        expected_manifest_sha256=expected_manifest_sha256)
    if (not isinstance(binding, dict) or set(binding) != {"url"} or
            not isinstance(binding["url"], str) or not binding["url"].startswith("ftdi://")):
        return {"ok": False, "fault": "operator", "reason": "Provide an explicit register binding with url", "_exit": 4}
    with open(os.path.join(pkg, "driver", "model.json"), encoding="utf-8") as stream:
        model = json.load(stream)
    ops = model.get("operations", {})
    steps = sum((ops.get(key, []) for key in ("init", "identify", "measure")), []) + model.get("state", [])
    allow_write = "write" in (allow_effects or [])
    if not allow_write and any(step.get("op") in ("reg_write", "raw_write") for step in steps):
        return {"ok": False, "fault": "operator", "reason": "Explicit write effect grant required", "_exit": 4}
    env = dict(os.environ, GD_REGISTER_URL=binding["url"], GD_REGISTER_ALLOW_WRITE="1" if allow_write else "0")
    checked = _register_integrity(pkg, model_dir, expected_manifest_sha256)
    if not checked["ok"]:
        return checked
    with tempfile.TemporaryDirectory() as temporary:
        snapshot = _register_snapshot(pkg, temporary, checked)
        verified = _register_integrity(snapshot, model_dir, checked["manifest_sha256"])
        if not verified["ok"]:
            return verified
        rc, out, err = core.sh([core.VENV_PY, "-I", "-B", os.path.join(snapshot, "tests", "test_live.py")],
                               cwd=snapshot, env=env, timeout=300)
    lines = [l for l in out.splitlines() if l.strip()]
    return {"ok": rc == 0, "passed": sum(1 for l in lines if l.startswith("PASS")),
            "failed": sum(1 for l in lines if l.startswith("FAIL")), "output": lines[-8:],
            "_exit": 0 if rc == 0 else 1, "_notes": ([err[-300:]] if rc != 0 and err else [])}
